name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
  checkstyle_job:
      runs-on: ubuntu-latest
      name: Checkstyle job
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run check style
          uses: nikitasavinov/checkstyle-action@master
          with:
            reporter: 'github-pr-check'
            tool_name: 'testtool'